name: ibmbushu
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install wget
        sudo apt-get -y install curl
    - name: Clone source
      run: |
        cd /home/runner
        wget https://public.dhe.ibm.com/cloud/bluemix/cli/bluemix-cli/1.1.0/binaries/IBM_Cloud_CLI_1.1.0_linux_amd64.tgz
        tar zxvf IBM_Cloud_CLI_1.1.0_linux_amd64.tgz
    - name: go kaishi
      run: |
        cd /home/runner/IBM_Cloud_CLI
        echo 7 | /home/runner/IBM_Cloud_CLI/ibmcloud login -u ${{ secrets.ibmuser }} -p ${{ secrets.ibmpasswd }}
        /home/runner/IBM_Cloud_CLI/ibmcloud target --cf
        /home/runner/IBM_Cloud_CLI/ibmcloud cf install
        mv /home/runner/work/ibmcfv2/ibmcfv2/manifest.yml /home/runner/IBM_Cloud_CLI/manifest.yml
        /home/runner/IBM_Cloud_CLI/ibmcloud cf push yanzi --docker-image byxiaopeng/ibm-docker:latest
    - name: WeChat notification
      run: curl https://sc.ftqq.com/SCU3787Te82950be8737ede8ba744210bdefaea35826a78d5c33a.send?text=IBMV2部署成功       
    - uses: actions/upload-artifact@master
      with:
        name: result
        path: /home/runner/IBM_Cloud_CLI/CF_CLI_SLC_Notices.txt
